-- ============================================================
-- Schema: quiz, SEB configuration, and student launch tables
--
-- This file reflects the live database schema as deployed.
-- It is a hand-maintained, commented version of the structure
-- produced by `pg_dump --schema-only` against the production
-- Neon database (PostgreSQL 17).
--
-- Note: the application sets `updated_at` on writes. There are
-- no database triggers maintaining `updated_at`; the columns
-- carry a `DEFAULT now()` for the initial insert only.
-- ============================================================


-- ============================================================
-- 1. Base quizzes table
--    Upserted every time we fetch from Canvas.
--    Stores just enough metadata to display in the dashboard
--    without re-calling Canvas.
-- ============================================================
CREATE TABLE IF NOT EXISTS quizzes (
  course_id   TEXT    NOT NULL,
  quiz_id     TEXT    NOT NULL,

  -- Canvas metadata (updated on every upsert)
  title       TEXT    NOT NULL DEFAULT 'Untitled Quiz',
  quiz_type   TEXT    NOT NULL DEFAULT 'classic',   -- 'classic' | 'new'

  -- Timestamps
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (course_id, quiz_id)
);


-- ============================================================
-- 2. SEB configuration files
--    One row per quiz. Inserted when the instructor completes
--    the SEB wizard and a .seb file is generated.
--    The file itself is stored as raw bytes.
-- ============================================================
CREATE TABLE IF NOT EXISTS seb_config_files (
  course_id       TEXT    NOT NULL,
  quiz_id         TEXT    NOT NULL,

  -- The generated .seb binary
  file_name       TEXT    NOT NULL,            -- e.g. 'Midterm_Exam_SEB_Config.seb'
  file_data       BYTEA   NOT NULL,            -- raw .seb file contents
  config_key      TEXT,                         -- SHA-256 config key hex string
  file_link       TEXT,                         -- URL for downloading the .seb file from Canvas
  access_code     TEXT,                         -- access code associated with this quiz
  canvas_quiz_url TEXT,                          -- Canvas quiz URL used as the SEB startURL

  -- Timestamps
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (course_id, quiz_id),
  FOREIGN KEY (course_id, quiz_id)
    REFERENCES quizzes (course_id, quiz_id)
    ON DELETE CASCADE
);


-- ============================================================
-- 3. SEB security settings
--    One row per quiz. Stores the individual settings the
--    instructor selected in the wizard.
--
--    Every column beyond the PK is nullable so we can insert
--    a bare row during the Canvas upsert and fill settings later.
-- ============================================================
CREATE TABLE IF NOT EXISTS seb_settings (
  course_id               TEXT    NOT NULL,
  quiz_id                 TEXT    NOT NULL,

  -- Browser controls
  force_fullscreen        BOOLEAN,

  -- System restrictions
  block_screen_sharing    BOOLEAN,
  block_virtual_machine   BOOLEAN,
  block_clipboard         BOOLEAN,
  block_printing          BOOLEAN,
  disable_spell_check     BOOLEAN,

  -- Network controls
  enable_url_filter       BOOLEAN,
  allowed_url_patterns    JSONB,     -- e.g. ["canvas.ufl.edu/*", "*.instructure.com/*"]

  -- Access control
  access_code             TEXT,
  ip_filter_enabled       BOOLEAN,
  allowed_ip_ranges       JSONB,     -- e.g. ["192.168.1.0/24"]

  -- Preset that was selected (if any)
  preset_name             TEXT,       -- 'standard' | 'high_security' | 'open_book' | 'testing_center' | null

  -- Timestamps
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (course_id, quiz_id),
  FOREIGN KEY (course_id, quiz_id)
    REFERENCES quizzes (course_id, quiz_id)
    ON DELETE CASCADE
);


-- ============================================================
-- 4. Users
--    One row per Canvas user who has authorized the tool via
--    OAuth. Stores the refresh token (and a short-lived access
--    token) used to act on the student's behalf during a launch.
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canvas_user_id    BIGINT  NOT NULL UNIQUE,

  -- Canvas profile metadata
  name              TEXT,
  email             TEXT,
  avatar_url        TEXT,
  canvas_domain     TEXT,

  -- OAuth tokens
  access_token      TEXT,
  refresh_token     TEXT,
  token_expires_at  TIMESTAMPTZ,

  -- Timestamps
  created_at        TIMESTAMPTZ DEFAULT now(),
  updated_at        TIMESTAMPTZ DEFAULT now()
);


-- ============================================================
-- 5. Launch sessions
--    One row per exam launch. Binds a single-use launch token
--    to a student, quiz, access code, and Config Key. The token
--    is embedded in the .seb file's startURL and is validated by
--    the SEB gate. Expires after a short window (~15 minutes).
-- ============================================================
CREATE TABLE IF NOT EXISTS launch_sessions (
  launch_token      TEXT    NOT NULL,
  canvas_user_id    BIGINT  NOT NULL,
  course_id         TEXT    NOT NULL,
  quiz_id           TEXT    NOT NULL,
  canvas_quiz_url   TEXT    NOT NULL,
  access_code       TEXT,
  config_key        TEXT,                        -- filled in after the .seb plist is built
  expires_at        TIMESTAMPTZ NOT NULL,
  used_at           TIMESTAMPTZ,                 -- set when the gate burns the token (single-use)
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (launch_token),
  FOREIGN KEY (canvas_user_id)
    REFERENCES users (canvas_user_id)
);

-- Index to support expiry lookups / cleanup of stale sessions
CREATE INDEX IF NOT EXISTS launch_sessions_expires_idx
  ON launch_sessions (expires_at);