import { Quiz } from "./types";

// Dummy quizzes for local development. Dates are spread across all the
// dashboard card states (past due, currently open, opens soon, opens later,
// missing dates) so the UI can be exercised without hitting Canvas.
//
// Today's date when last refreshed: April 24, 2026.
export const DUMMY_QUIZZES: Quiz[] = [
  // ─── Past due — exam window has closed ─────────────────────────────────
  {
    id: "q-1001",
    courseId: "c-101",
    title: "Midterm Exam",
    description: "Covers chapters 1-8. Safe Exam Browser required.",
    dueAt: "2026-04-17T23:59:00Z",
    lockAt: "2026-04-18T00:00:00Z",
    unlockAt: "2026-04-10T08:00:00Z",
    published: true,
    pointsPossible: 100,
    questionCount: 50,
    timeLimitSeconds: 5400,
    hasAccessCode: true,
    accessCode: "MIDTERM-2026",
    allowedAttempts: 1,
    shuffleQuestions: true,
    shuffleAnswers: true,
    oneAtATime: true,
    allowBacktracking: false,
    quizType: "new",
    assignmentGroupId: "ag-1",
    sebConfigured: true,
    sebConfiguredDate: "2026-04-08T14:30:00Z",
    sebSettings: {
      securityLevel: "high",
      allowScreenSharing: false,
      allowVirtualMachine: false,
      allowSpellCheck: false,
      browserViewMode: 1,
      urlFilterEnabled: true,
      allowedDomains: ["canvas.ufl.edu", "*.instructure.com"],
      accessCode: "SEB-MID-2026",
      configuredAt: "2026-04-08T14:30:00Z",
    },
  },

  // ─── Currently open — exam is live, students can access ────────────────
  {
    id: "q-1002",
    courseId: "c-101",
    title: "Chapter 5 Quiz",
    description: "Short quiz on key concepts from chapter 5.",
    dueAt: "2026-05-06T23:59:00Z",
    lockAt: "2026-05-07T00:00:00Z",
    unlockAt: "2026-04-22T00:00:00Z",
    published: true,
    pointsPossible: 25,
    questionCount: 15,
    timeLimitSeconds: 1800,
    hasAccessCode: false,
    allowedAttempts: 2,
    shuffleQuestions: true,
    shuffleAnswers: true,
    oneAtATime: false,
    allowBacktracking: true,
    quizType: "classic",
    assignmentGroupId: "ag-2",
    sebConfigured: false,
    sebConfiguredDate: null,
    sebSettings: null,
  },

  // ─── Upcoming (more than 3 days out) — neutral styling ─────────────────
  {
    id: "q-1003",
    courseId: "c-101",
    title: "Final Exam",
    description: "Comprehensive final covering all course material.",
    dueAt: "2026-05-15T23:59:00Z",
    lockAt: "2026-05-16T00:00:00Z",
    unlockAt: "2026-05-08T08:00:00Z",
    published: false,
    pointsPossible: 200,
    questionCount: 80,
    timeLimitSeconds: 7200,
    hasAccessCode: false,
    allowedAttempts: 1,
    shuffleQuestions: true,
    shuffleAnswers: true,
    oneAtATime: true,
    allowBacktracking: false,
    quizType: "new",
    assignmentGroupId: "ag-1",
    sebConfigured: false,
    sebConfiguredDate: null,
    sebSettings: null,
  },

  // ─── Opens soon (within 3 days) — amber "heads up" styling ─────────────
  {
    id: "q-1004",
    courseId: "c-101",
    title: "Lab Practical #2",
    description: "Hands-on lab assessment. Open notes permitted.",
    dueAt: "2026-04-26T17:00:00Z",
    lockAt: "2026-04-26T18:00:00Z",
    unlockAt: "2026-04-26T13:00:00Z",
    published: true,
    pointsPossible: 50,
    questionCount: 30,
    timeLimitSeconds: 3600,
    hasAccessCode: true,
    accessCode: "LAB2-2026",
    allowedAttempts: 1,
    shuffleQuestions: false,
    shuffleAnswers: false,
    oneAtATime: true,
    allowBacktracking: true,
    quizType: "classic",
    assignmentGroupId: "ag-3",
    sebConfigured: true,
    sebConfiguredDate: "2026-04-15T09:15:00Z",
    sebSettings: {
      securityLevel: "standard",
      allowScreenSharing: false,
      allowVirtualMachine: false,
      allowSpellCheck: true,
      browserViewMode: 1,
      urlFilterEnabled: true,
      allowedDomains: ["canvas.ufl.edu", "*.instructure.com"],
      accessCode: "SEB-LAB-2026",
      configuredAt: "2026-04-15T09:15:00Z",
    },
  },

  // ─── No access date but has a due date ─────────────────────────────────
  {
    id: "q-1005",
    courseId: "c-101",
    title: "Reading Comprehension Quiz",
    description: null,
    dueAt: "2026-05-01T23:59:00Z",
    lockAt: null,
    unlockAt: null,
    published: true,
    pointsPossible: 10,
    questionCount: 8,
    timeLimitSeconds: null,
    hasAccessCode: true,
    accessCode: "READ-2026",
    allowedAttempts: 3,
    shuffleQuestions: false,
    shuffleAnswers: true,
    oneAtATime: false,
    allowBacktracking: true,
    quizType: "new",
    assignmentGroupId: "ag-2",
    sebConfigured: false,
    sebConfiguredDate: null,
    sebSettings: null,
  },

  // ─── No dates at all ───────────────────────────────────────────────────
  {
    id: "q-1006",
    courseId: "c-101",
    title: "Practice Exam (Ungraded)",
    description: "Optional practice exam. Does not count toward your grade.",
    dueAt: null,
    lockAt: null,
    unlockAt: null,
    published: true,
    pointsPossible: 0,
    questionCount: 25,
    timeLimitSeconds: null,
    hasAccessCode: false,
    allowedAttempts: -1,
    shuffleQuestions: true,
    shuffleAnswers: true,
    oneAtATime: false,
    allowBacktracking: true,
    quizType: "classic",
    assignmentGroupId: null,
    sebConfigured: false,
    sebConfiguredDate: null,
    sebSettings: null,
  },
];