import { Quiz } from "./types";

export const DUMMY_QUIZZES: Quiz[] = [
  {
    id: "q-1001",
    courseId: "c-101",
    title: "Midterm Exam",
    description: "Covers chapters 1-8. Safe Exam Browser required.",
    dueAt: "2027-03-15T23:59:00Z",
    lockAt: "2027-03-16T00:00:00Z",
    unlockAt: "2027-03-15T08:00:00Z",
    published: true,
    pointsPossible: 100,
    questionCount: 50,
    timeLimitSeconds: 5400,
    hasAccessCode: true,
    allowedAttempts: 1,
    shuffleQuestions: true,
    shuffleAnswers: true,
    oneAtATime: true,
    allowBacktracking: false,
    quizType: "new",
    assignmentGroupId: "ag-1",
    sebConfigured: true,
    sebConfiguredDate: "2027-02-20T14:30:00Z",
    sebSettings: {
      securityLevel: "high",
      allowQuit: false,
      allowScreenSharing: false,
      allowVirtualMachine: false,
      allowSpellCheck: false,
      browserViewMode: 1,
      urlFilterEnabled: true,
      allowedDomains: ["canvas.ufl.edu", "*.instructure.com"],
      accessCode: "SEB-MID-2027",
      configuredAt: "2027-02-20T14:30:00Z",
    },
  },
  {
    id: "q-1002",
    courseId: "c-101",
    title: "Chapter 5 Quiz",
    description: "Short quiz on key concepts from chapter 5.",
    dueAt: "2026-03-01T23:59:00Z",
    lockAt: "2026-03-02T00:00:00Z",
    unlockAt: "2026-03-01T00:00:00Z",
    published: true,
    pointsPossible: 25,
    questionCount: 15,
    timeLimitSeconds: 1800,
    hasAccessCode: false,
    allowedAttempts: 2,
    shuffleQuestions: true,
    shuffleAnswers: true,
    oneAtATime: false,
    allowBacktracking: true,
    quizType: "classic",
    assignmentGroupId: "ag-2",
    sebConfigured: false,
    sebConfiguredDate: null,
    sebSettings: null,
  },
  {
    id: "q-1003",
    courseId: "c-101",
    title: "Final Exam",
    description: "Comprehensive final covering all course material.",
    dueAt: "2026-04-20T23:59:00Z",
    lockAt: "2026-04-21T00:00:00Z",
    unlockAt: "2026-04-20T08:00:00Z",
    published: false,
    pointsPossible: 200,
    questionCount: 80,
    timeLimitSeconds: 7200,
    hasAccessCode: false,
    allowedAttempts: 1,
    shuffleQuestions: true,
    shuffleAnswers: true,
    oneAtATime: true,
    allowBacktracking: false,
    quizType: "new",
    assignmentGroupId: "ag-1",
    sebConfigured: false,
    sebConfiguredDate: null,
    sebSettings: null,
  },
  {
    id: "q-1004",
    courseId: "c-101",
    title: "Lab Practical #2",
    description: "Hands-on lab assessment. Open notes permitted.",
    dueAt: "2026-03-10T17:00:00Z",
    lockAt: "2026-03-10T18:00:00Z",
    unlockAt: "2026-03-10T13:00:00Z",
    published: true,
    pointsPossible: 50,
    questionCount: 30,
    timeLimitSeconds: 3600,
    hasAccessCode: true,
    allowedAttempts: 1,
    shuffleQuestions: false,
    shuffleAnswers: false,
    oneAtATime: true,
    allowBacktracking: true,
    quizType: "classic",
    assignmentGroupId: "ag-3",
    sebConfigured: true,
    sebConfiguredDate: "2026-02-18T09:15:00Z",
    sebSettings: {
      securityLevel: "standard",
      allowQuit: false,
      allowScreenSharing: false,
      allowVirtualMachine: false,
      allowSpellCheck: true,
      browserViewMode: 1,
      urlFilterEnabled: true,
      allowedDomains: ["canvas.ufl.edu", "*.instructure.com"],
      accessCode: "SEB-LAB-2026",
      configuredAt: "2026-02-18T09:15:00Z",
    },
  },
  {
    id: "q-1005",
    courseId: "c-101",
    title: "Reading Comprehension Quiz",
    description: null,
    dueAt: "2026-02-28T23:59:00Z",
    lockAt: null,
    unlockAt: null,
    published: true,
    pointsPossible: 10,
    questionCount: 8,
    timeLimitSeconds: null,
    hasAccessCode: true,
    allowedAttempts: 3,
    shuffleQuestions: false,
    shuffleAnswers: true,
    oneAtATime: false,
    allowBacktracking: true,
    quizType: "new",
    assignmentGroupId: "ag-2",
    sebConfigured: false,
    sebConfiguredDate: null,
    sebSettings: null,
  },
  {
    id: "q-1006",
    courseId: "c-101",
    title: "Practice Exam (Ungraded)",
    description: "Optional practice exam. Does not count toward your grade.",
    dueAt: null,
    lockAt: null,
    unlockAt: null,
    published: true,
    pointsPossible: 0,
    questionCount: 25,
    timeLimitSeconds: null,
    hasAccessCode: false,
    allowedAttempts: -1,
    shuffleQuestions: true,
    shuffleAnswers: true,
    oneAtATime: false,
    allowBacktracking: true,
    quizType: "classic",
    assignmentGroupId: null,
    sebConfigured: false,
    sebConfiguredDate: null,
    sebSettings: null,
  },
];