import { Quiz } from "./types";

export const DUMMY_QUIZZES: Quiz[] = [
  {
    id: "q-1001",
    title: "Midterm Exam",
    dueAt: "2026-03-15T23:59:00Z",
    pointsPossible: 100,
    questionCount: 50,
    published: true,
    sebConfigured: true,
    sebSettings: {
      securityLevel: "high",
      allowQuit: false,
      allowScreenSharing: false,
      allowVirtualMachine: false,
      allowSpellCheck: false,
      browserViewMode: 1,
      urlFilterEnabled: true,
      allowedDomains: ["canvas.ufl.edu", "*.instructure.com"],
      accessCode: "SEB-MID-2026",
      configuredAt: "2026-02-20T14:30:00Z",
    },
  },
  {
    id: "q-1002",
    title: "Chapter 5 Quiz",
    dueAt: "2026-03-01T23:59:00Z",
    pointsPossible: 25,
    questionCount: 15,
    published: true,
    sebConfigured: false,
  },
  {
    id: "q-1003",
    title: "Final Exam",
    dueAt: "2026-04-20T23:59:00Z",
    pointsPossible: 200,
    questionCount: 80,
    published: false,
    sebConfigured: false,
  },
  {
    id: "q-1004",
    title: "Lab Practical #2",
    dueAt: "2026-03-10T17:00:00Z",
    pointsPossible: 50,
    questionCount: 30,
    published: true,
    sebConfigured: true,
    sebSettings: {
      securityLevel: "standard",
      allowQuit: false,
      allowScreenSharing: false,
      allowVirtualMachine: false,
      allowSpellCheck: true,
      browserViewMode: 1,
      urlFilterEnabled: true,
      allowedDomains: ["canvas.ufl.edu", "*.instructure.com"],
      accessCode: "SEB-LAB-2026",
      configuredAt: "2026-02-18T09:15:00Z",
    },
  },
  {
    id: "q-1005",
    title: "Reading Comprehension Quiz",
    dueAt: "2026-02-28T23:59:00Z",
    pointsPossible: 10,
    questionCount: 8,
    published: true,
    sebConfigured: false,
  },
  {
    id: "q-1006",
    title: "Practice Exam (Ungraded)",
    dueAt: null,
    pointsPossible: 0,
    questionCount: 25,
    published: true,
    sebConfigured: false,
  },
];
